on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged}}
    runs-on: ubuntu-latest

    steps:
    - name: deploying to the frontend production server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.GLOBAL_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{secrets.private_key}}
        script_stop: true
        script: |
          . ~/.nvm/nvm.sh
          cd /var/www/G2-frontend/client
          git pull
          npm ci
          npm run build

